### ISSUE TITLE
Does your App work with USB Drives plugged into router??

### ISSUE THREAD

**Issue by NoBadMojo** [tjibbevanderlaan/chromeos-filesystem-sftp#106]
Hi there,
I would love to have your app work w. my external hard drive plugged into my router. Will it work?
Specifics:
Acer Chromebook c720p and Dual Band ASUS Router.  Iomega usb 2.0 hDD made by Samsung

I can successfully view files in my web browser, so I think I have that part set up correctly.  The drive will not mount...I;ve checked stuff like my port number. I can get it to where it doesnt show error messages..it just wont mount

Thanks for any help

**Comment by yoichiro** [comment]
If your router supports the SFTP, you will be able to mount the drive with this app.
