### ISSUE TITLE
Saving an image from a browser tab fails

### ISSUE THREAD

**Issue by wesort** [tjibbevanderlaan/chromeos-filesystem-sftp#107]
To recreate issue:
- Right-click > Save image as 
- Navigate to a mounted drive
- Save
- Error in download bar dialogue 

![failed-save-as](https://cloud.githubusercontent.com/assets/3920126/10700187/f5787968-79b3-11e5-9596-649ae80ac7a7.png)

Mounted drive working beautifully otherwise.

**Comment by yoichiro** [comment]
This is an issue of Chrome OS.
