### ISSUE TITLE
Print fingerprint in common formats

### ISSUE THREAD

**Issue by perguth** [tjibbevanderlaan/chromeos-filesystem-sftp#122]
![screenshot 2017-12-02 at 1 30 28 am](https://user-images.githubusercontent.com/85259/33509274-6bf64416-d700-11e7-93e4-d1183e35ec17.png)

Please print it out common fingerprint formats (or at least md5). Eg. like: https://gist.github.com/perguth/2b19304c1510467ce8e957a7fa3efffa

**Comment by yoichiro** [comment]
The format of the fingerprint has already been changed in the current version as like the following:

![screenshot 2019-02-21 at 06 08 19](https://user-images.githubusercontent.com/261787/53124730-70336780-359f-11e9-8366-2bca8a7cff95.png)
