### ISSUE TITLE
Remove!!!

### ISSUE THREAD

**Issue by Dingledoodie** [tjibbevanderlaan/chromeos-filesystem-sftp#127]
I can't get this to work for me. As soon as I turn on my Chromebook it says the app is taking too long, so I click abort. I just want it off my Chromebook now but I can't even close it as it says files are open and I must close them. How do I remove it, please?

**Comment by yoichiro** [comment]
@Dingledoodie You can uninstall this by the same way to uninstall other all Chrome apps.
