### ISSUE TITLE
Allow multiple mounts with same server/port/user with different mount point

### ISSUE THREAD

**Issue by ALovedOne** [tjibbevanderlaan/chromeos-filesystem-sftp#139]
In js/model/sftp_fs.js createFileSystemID only accepts user, server, port. Could it also include mountPath as well?

**Comment by yoichiro** [comment]
Actually, if we can mount a server per mount point, it would be very useful.

@tjibbevanderlaan If you also can agree this idea, I intend to modify the code to support this idea. How do you think about that?

**Comment by tjibbevanderlaan** [comment]
Hi Yoichiro,

Yes I definitely like this idea. By the way, if you would like to receive
the ownership on the repository again, please let me know :)

Best regards,
Tjibbe

Op ma 8 apr. 2019 om 23:48 schreef Yoichiro Tanaka <notifications@github.com

**Comment by yoichiro** [comment]
> By the way, if you would like to receive the ownership on the repository again, please let me know

@tjibbevanderlaan Sorry, I don't think so.

**Comment by yoichiro** [comment]
I'm busy a bit on this week. I intend to handle this issue from next week.
