### ISSUE TITLE
Connects all now fail

### ISSUE THREAD

**Issue by sloftin** [tjibbevanderlaan/chromeos-filesystem-sftp#82]
This has been working beautifully for a couple of months.  In the last couple of days, none of my saved connections work (to different hosts).  I can SSH to them all just fine, but SFTP now gives me connect (1111) errors on everything.

**Comment by yoichiro** [comment]
@sloftin Could you confirm the debug log on the console tab of the DevTools by the steps? https://github.com/yoichiro/chromeos-filesystem-sftp/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
Close this issue because we can't get enough information to solve this issue.
