### ISSUE TITLE
Allow recognizable server name in kept connections

### ISSUE THREAD

**Issue by hullian68** [tjibbevanderlaan/chromeos-filesystem-sftp#83]
It is nice to be able to retain a list of servers to which one has previously connected ("KEEP").  However, I have a number of remote servers which are only known by their numeric IP address (e.g., 111.222.333.444) and don't have a DNS name to use as a mnemonic.  Would it be possible to add a label or nickname field to each server record so that one can easily distinguish between servers which have similar IP addresses?  Thanks.

**Comment by yoichiro** [comment]
In the current version, you can specify a display name for each kept connection information.
