### ISSUE TITLE
I get an error every time I try to add your app on chrome os Dev build

### ISSUE THREAD

**Issue by thakyZ** [tjibbevanderlaan/chromeos-filesystem-sftp#87]
I get an error every time I try to install this app on my Chrome OS device. This is the error: `Package is invalid. Details: 'The 'fileSystemProvider' permission requires the 'file_system_provider_capabilities' section to be specified in the manifest.'.`

I am running on Chrome OS build: 44.0.2403.5 dev (64-bit)

**Comment by mtomasz-chromium** [comment]
44.0.2403.5 dev release has a bug. Please wait for the next dev push.

**Comment by yoichiro** [comment]
@thakyZ Can you think that this issue was solved?

**Comment by yoichiro** [comment]
Basically, the Chrome OS Dev Build is buggy.
