### ISSUE TITLE
Not seeing SFTP dialog

### ISSUE THREAD

**Issue by yahavatar** [tjibbevanderlaan/chromeos-filesystem-sftp#90]
I just installed this app from the Web Store and when I click on the SFTP icon in my apps, nothing seems to happen. No dialog, no message at all. I Opened the Google Task Manager and I can see a process being spawned called: 

Background Page: SFTP File System

But it disappears after 10-15 seconds. Any help would be great. Thanks, yah.

**Comment by yoichiro** [comment]
@yahavatar This application can work ChromeOS only. Did you install this application into your ChromeOS?
