### ISSUE TITLE
Does this work in an an app's file-picker?

### ISSUE THREAD

**Issue by mark-hahn** [tjibbevanderlaan/chromeos-filesystem-sftp#97]
I am running an ssh server in my crouton chroot on a pixel 2015.  I can mount the localhost sftp in the files app and access all files in the chroot which is awesome.

When I open a file dialog from a chromeos app, like using `Add folder to workspace` in the chrome dev tools inspector, I only see the Downloads folder.  There is a button `+ Add new services` in that dialog but this service doesn't show in the list.  I assume this is because I already added the service to the files app and it has been removed from the list.

If I leave the app dialog open and do `Mount a new SFTP server` it doesn't add the service to the dialog.

Is there any way to use this service in an app's file-picker?

**Comment by yoichiro** [comment]
Unfortunately, there is no way to show the mounted point on the file picker dialog. This is a limitation of the current Chrome OS.
