### ISSUE TITLE
Authentication type "Password" is not supported 0 11

### ISSUE THREAD

**Issue by Martyfree123** [tjibbevanderlaan/chromeos-filesystem-sftp#99]
I'm trying to connect to my home computer via SFTP on my Asus C300 Chromebook. Everything is setup correctly but whenever I try to connect is says "Authentication type "Password" is not supported 0 11" Is anyone else having this issue? Could we get some kind of fix? Thanks.

**Comment by rfilmyer** [comment]
Ensure that your ssh server actually supports password authentication. Some servers, by default, do not.

For example, a Mac OS X (Yosemite) installation, by default, only supports `publickey` and `keyboard-interactive`.

Only reason I'm saying this is because it just happened to me :sweat:
